#!/usr/bin/bash
pycodestyle *.py
# check modules documentation
#python3 -c 'print(__import__("*").__doc__)'

# Classes definition
#python3 -c 'print(__import__("my_module").MyClass.__doc__'

#functions should have definition
#python3 -c 'print(__import__("my_module").my_function.__doc__)'
